### ISSUE TITLE
Compilation error: Undeclared identifier

### ISSUE THREAD

**Issue by thisago** [openpeeps/bro#3]
At `src/bropkg/engine/parser.nim(603, 21)` error: `Error: undeclared identifier: 'parseNamedColor'`

Nim version tested: 1.9.5 and 1.6.10

https://github.com/openpeeps/bro/commit/83ab67e080c3271c431459f797534378a2d559b6#r123334126

**Comment by georgelemon** [comment]
I forgot to push some handlers. I'm planning to use [treeform/chroma](https://github.com/treeform/chroma) for color handlers.
